services:
  python-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    # ...

  postgres:
    build:
      context: .
      dockerfile: infra/postgres/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - pgdb-store:/var/lib/postgresql/data
    tty: true
    environment:
      POSTGRES_PASSWORD: 'postgres'

  minio:
    build:
      context: .
      dockerfile: infra/minio/Dockerfile
    command: ['server', '/data', '--console-address', ':9090']
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio-store:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password

volumes:
  pgdb-store:
  minio-store:
